# Generated by Django 3.0.6 on 2020-05-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_auto_20200524_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='since',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
