# Generated by Django 3.0.6 on 2020-05-16 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatechatroom',
            name='user1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='privatechatroom',
            name='user2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
