# Generated by Django 3.0.6 on 2020-05-16 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0005_auto_20200516_1546'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='privatechatroom',
            name='unique_pm2',
        ),
    ]
