# Generated by Django 3.0.6 on 2020-05-16 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Chat', '0006_auto_20200516_1547'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='privatechatroom',
            name='unique_pm',
        ),
        migrations.AlterField(
            model_name='privatechatroom',
            name='user1',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='privatechatroom',
            name='user2',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL),
        ),
    ]
