# Generated by Django 3.0.6 on 2020-05-16 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Chat', '0007_auto_20200516_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatechatroom',
            name='chatroom_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='privatechatroom',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='privatechatroom',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL),
        ),
    ]
