# Generated by Django 3.0.6 on 2020-05-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0010_auto_20200516_1652'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chatroomuser',
            name='unique_user_chatroom',
        ),
        migrations.RenameField(
            model_name='chatroomuser',
            old_name='chatroom_id',
            new_name='chatroom',
        ),
        migrations.AddConstraint(
            model_name='chatroomuser',
            constraint=models.UniqueConstraint(fields=('chatroom', 'user'), name='unique_user_chatroom'),
        ),
    ]
