# Generated by Django 3.0.6 on 2020-05-16 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Chat', '0002_auto_20200516_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatechatroom',
            name='user1_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='privatechatroom',
            name='user2_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='privatechatroom',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='privatechatroom',
            constraint=models.UniqueConstraint(fields=('user1_id', 'user2_id'), name='unique_pm'),
        ),
    ]
