# Generated by Django 3.0.6 on 2020-12-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0013_privatemessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatechatroom',
            name='id',
        ),
        migrations.AlterField(
            model_name='privatechatroom',
            name='chatroom_id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
