# Generated by Django 3.0.6 on 2020-12-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0014_auto_20201202_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='chatroom_id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
