# Generated by Django 3.0.6 on 2020-12-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0015_auto_20201202_1744'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='privatechatroom',
            constraint=models.UniqueConstraint(fields=('user1', 'user2'), name='unique_private_chatroom'),
        ),
    ]
