# Generated by Django 3.0.6 on 2021-03-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0018_auto_20210319_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatemessage',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
