# Generated by Django 3.0.6 on 2021-03-30 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0020_auto_20210320_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroomuser',
            name='chatroom',
        ),
        migrations.RemoveField(
            model_name='chatroomuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='Chatroom',
        ),
        migrations.DeleteModel(
            name='ChatroomUser',
        ),
    ]
